ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDf2IP9/3BmF11a2359zZospBcGfxrxqOYPCaOaXD4WoTerXWoI/3lE+NnCUaouSg99Cm3hJ0NgYH+qPwYzJVBz8chPVRh14F8063S03T/l4y12CQqoRqJpFcvfI9bEdfzzj9TZ4XsgMiArltgHVFaQqxo+aq7SL2pRBzk9hRUvwSL/swB00O3gOitaGe/T98HTgSSuW4KjMhPe7q5ZdpI3y7aFZFxH52xwy0397sQEP1Ky5s10DwfGqEmU9gleVm8SOs18f8gcLm17xDLWxd4c39Sw49XGZfnEqyJFYTgmh50n2d+B3K1NWAoEiM7EWhy28HaUt9u8fmi+9f/hPQ+qGILInq5A8PiQFo0REBVWIuW3HchjWjCOaIkLp28ZU2wlwcojvb10s2pv5arIbMKeMp92T8QhrgIjA+mDkiRC21bgkDmIm8hTZ8rDuPZFpVjC0wdAYcMz3ZzvNl5o7TZMlFXeIftMiRoYFqRfmwcEwopwlg5y06IjeyqUzdAButfTrfJB02km1JmscItsKm0ImygGjLgrAUvVDF929a2V6sXQ3uNx/AVWuRAN6dLQkg26ULNuk7343/7MYXA1qJ68zm6UShZZwT+67qGQ3YprfYrxc1IRnMb4/W5Om3DfIOcvQS7prLWP64zA9mIRPs/uuA8wWsGe3LWLPdizUenkXw==
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkec0ME7Hc7ff/8oi8GGTCc5LQfzS+ZIkDNXLhFdtDD7IBoaev6yp53V3vYuv/n2gn/iHqtAm4qt/cuneO8DubRU1Lck94QbW1tIP7750UGY6G/YvJ1HK+yDGZrHP3Uq3Wout9pfUZuzxlVoNhLNuYLpNE9TXNUsGT7E8PUKLljSxO2yT9l3aZjM6K+3IbQDZ1fUpMGfxngNXW1lkxXoFeH7ooo852UWgfdsepx9Cx1V3LJ5QNIoxchle9cwgkzZpqSD1Zm3ppB+cKulj9Q1sVLQY79SFJYqf+KTyLTJimqsBQD28DGUmvC5nhMvARExIoPS0V2C8IaFKGch9yq4ztpM1o38WBsxCNkJ/c/DGdMmu8t6UYxQJRx6OokAwF2X3aiCsW5BukaVeFce7eEco7xqhPz0LmoqpaWqhPofWUUcqVVz4kBRO9SYrtVRcgx28bTccoon2hRRWLs6u6Dn4fVFA+r1ZVyvfp2MU3BuMGLHTLr8tbNzsL1uhEcp0c5Kiap9TPRgFHebzNla2H5xMCaXf88s9hrPFIopxwZy338JHyFViemzCa2y8Go0w0csOMBOFbeaHrQdDVM7M2qrrscli/SwFQGUVx0U+N9hbkvOYRT/09j9TE9TBDNjrVCIuV648NtSSSwHP9k/NAJHk/9wHXoPyNlTxZ2eRE4xDDOw==
hostname: loki
write_files:
- content: |-
    /dev/cdrom    /media/cdrom  iso9660 noauto,ro 0 0
    /dev/usbdisk  /media/usb    vfat    noauto,ro 0 0
    /dev/vdb      /mnt/disk1    ext4    auto      0 0
    /dev/vdc      /mnt/disk2    ext4    auto      0 0
    /dev/vdd      /mnt/disk3    ext4    auto      0 0
    /dev/nvme0n1  /mnt/nvme1    ext4    auto      0 0
    /dev/nvme1n1  /mnt/nvme2    ext4    auto      0 0
  owner: root
  path: /etc/fstab
  permissions: '0644'
k3os:
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.de.pool.ntp.org
  - 1.de.pool.ntp.org
  token: NoxHomeCluster
  k3s_args:
  - server
  - "--no-deploy=traefik"